import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it} from "vitest";
import {EnterpriseAdminApp,PermissionGuard} from "../src/features/admin/EnterpriseAdminApp";
import {InMemoryEnterpriseAdminService} from "../src/features/admin/enterpriseAdminService";
import type {EnterprisePrincipal} from "../src/features/admin/enterpriseAdmin.types";
const principal=(role:EnterprisePrincipal["roles"][number],tenantId="development-tenant",permissions:readonly string[]=Object.freeze([])):EnterprisePrincipal=>Object.freeze({actorId:`${role}-actor`,tenantId,roles:Object.freeze([role]),permissions});
describe("Enterprise Administration",()=>{
 it("renderiza dashboard global, navegación completa, métricas y estado accesible",async()=>{history.replaceState({},"","/admin");const service=new InMemoryEnterpriseAdminService(principal("platform-admin"));render(<EnterpriseAdminApp service={service}/>);expect(await screen.findByRole("heading",{name:"Control empresarial"})).toBeInTheDocument();expect(screen.getByText("Visión global")).toBeInTheDocument();expect(screen.getByText("Datos deterministas de desarrollo · no facturados")).toBeInTheDocument();expect(screen.getByRole("complementary",{name:"Administración"})).toBeInTheDocument();expect(screen.getByRole("img",{name:/Actividad determinista/})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Empresas"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Estado del sistema"})).toBeInTheDocument();});
 it("aísla tenant y usuario y muestra guard de permisos",async()=>{const tenantService=new InMemoryEnterpriseAdminService(principal("tenant-admin","development-tenant",Object.freeze(["assistants:read"])));const tenants=await tenantService.list("tenants",{page:1,pageSize:20});const users=await tenantService.list("users",{page:1,pageSize:20});expect(tenants.items).toHaveLength(1);expect(users.items.every(item=>item.tenantId==="development-tenant")).toBe(true);await expect(tenantService.create("users",{name:"Intruso",tenantId:"tenant-north"})).rejects.toThrow(/cruzado/);render(<PermissionGuard service={tenantService} permission="security:update"><button>prohibido</button></PermissionGuard>);expect(screen.getByRole("alert")).toHaveTextContent("security:update");});
 it("ejecuta operaciones funcionales, estados, roles, invitaciones, costos y auditoría",async()=>{const service=new InMemoryEnterpriseAdminService(principal("platform-admin"));const tenant=await service.create("tenants",{name:"Acme Demo",slug:"acme-demo"});expect(tenant.status).toBe("active");const invitation=await service.create("invitations",{tenantId:String(tenant.tenantId),email:"admin@acme.test",role:"tenant-admin",expiresAt:"2026-08-11T12:00:00.000Z"});expect(invitation.email).toBe("admin@acme.test");const role=await service.create("roles",{tenantId:String(tenant.tenantId),name:"Editor",permissions:Object.freeze(["assistants:read","assistants:update"])});const user=await service.create("users",{tenantId:String(tenant.tenantId),name:"Admin Acme",roleId:String(role.id),status:"active"});expect(user.roleId).toBe(role.id);await service.update("users",String(user.id),{status:"suspended"});expect((await service.list("users",{tenantId:String(tenant.tenantId),page:1,pageSize:20})).items.find(item=>item.id===user.id)?.status).toBe("suspended");expect(await service.archive("tenants",String(tenant.id))).toBe(true);expect((await service.list("costs",{page:1,pageSize:20})).items[0]?.billed).toBe(false);expect((await service.list("audit",{page:1,pageSize:100})).total).toBeGreaterThanOrEqual(5);});
 it("cubre recursos operativos, redacción, búsqueda, orden, paginación y exportaciones",async()=>{const service=new InMemoryEnterpriseAdminService(principal("platform-admin"));for(const resource of ["assistants","knowledge","documents","ingestion","conversations","tools","providers","usage","metrics","security","settings","status"] as const)expect((await service.list(resource,{page:1,pageSize:20})).total).toBeGreaterThan(0);const conversations=await service.list("conversations",{search:"redactado",page:1,pageSize:20,sort:"id",direction:"desc"});expect(conversations.items[0]?.message).toBe("[CONTENIDO REDACTADO]");const first=await service.list("users",{page:1,pageSize:1,sort:"name",direction:"asc"});expect(first.hasNext).toBe(true);expect((await service.list("users",{search:"North",page:1,pageSize:20})).total).toBe(1);expect(await service.export("users","json")).not.toMatch(/password|secret/i);expect(await service.export("conversations","csv")).not.toContain("CONTENIDO REDACTADO");});
 it("permite crear desde UI, filtrar, paginar, confirmar archivado y abrir Studio",async()=>{history.replaceState({},"","/admin/tenants");const user=userEvent.setup();const service=new InMemoryEnterpriseAdminService(principal("platform-admin"));render(<EnterpriseAdminApp service={service}/>);expect(await screen.findByRole("heading",{name:"Empresas"})).toBeInTheDocument();await user.type(screen.getByPlaceholderText("Buscar…"),"Northwind");await waitFor(()=>expect(screen.getByText("Northwind Demo")).toBeInTheDocument());await user.clear(screen.getByPlaceholderText("Buscar…"));await user.click(screen.getByRole("button",{name:"Crear"}));expect(screen.getByRole("dialog")).toHaveAttribute("aria-modal","true");await user.type(screen.getByLabelText("Nombre"),"Nueva Empresa");await user.type(screen.getByLabelText("Detalle o slug"),"nueva-empresa");await user.click(screen.getByRole("button",{name:"Crear recurso"}));await waitFor(()=>expect(screen.getByText("Nueva Empresa")).toBeInTheDocument());expect(screen.getAllByRole("button",{name:"Archivar"}).length).toBeGreaterThan(0);});
});
