import type { KnowledgeManagerPermission, KnowledgeManagerPrincipal } from "@gano-bot/ai-core/knowledge-manager";
import { KnowledgeManagerError, KnowledgeManagerService } from "@gano-bot/ai-core/knowledge-manager";
import { BackendApiError } from "../errors.js";
import type { ApiPermission, ApiPrincipal } from "../contracts.js";
const ALL: readonly KnowledgeManagerPermission[] = Object.freeze(["knowledge:read", "knowledge:create", "knowledge:update", "knowledge:delete", "knowledge:archive", "knowledge:restore", "knowledge:associate", "documents:read", "documents:create", "documents:update", "documents:delete", "documents:reprocess", "ingestion:read", "ingestion:execute", "ingestion:cancel", "versions:read", "versions:restore"]);
function apiPermission(permission: KnowledgeManagerPermission): ApiPermission { if (permission === "documents:read" || permission === "versions:read" || permission === "ingestion:read") return "knowledge:read"; if (permission === "documents:create") return "knowledge:create"; if (permission === "documents:delete") return "knowledge:delete"; if (permission === "ingestion:execute") return "ingestion:execute"; if (permission === "knowledge:create" || permission === "knowledge:read" || permission === "knowledge:update" || permission === "knowledge:delete") return permission; return "knowledge:update"; }
function principal(value: ApiPrincipal): KnowledgeManagerPrincipal { const admin = value.permissions.includes("admin:*"); const allowed = ALL.filter((permission) => admin || value.permissions.includes(apiPermission(permission))); return Object.freeze({ actorId: value.actorId, tenantId: value.tenantId, permissions: Object.freeze(allowed) }); }
function body(value: unknown): Readonly<Record<string, unknown>> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new BackendApiError("BAD_REQUEST", "El cuerpo debe ser un objeto.", 400); return value as Readonly<Record<string, unknown>>; }
function normalize(error: unknown): never { if (error instanceof KnowledgeManagerError) { const status = error.code === "NOT_FOUND" ? 404 : error.code === "FORBIDDEN" || error.code === "TENANT_MISMATCH" ? 403 : error.code === "CONFLICT" ? 409 : 400; throw new BackendApiError(status === 404 ? "KNOWLEDGE_NOT_FOUND" : status === 403 ? "FORBIDDEN" : status === 409 ? "CONFLICT" : "BAD_REQUEST", error.message, status, undefined, error); } throw error; }
export interface KnowledgeManagerRouteContext { readonly principal: ApiPrincipal; readonly readJson: () => Promise<unknown>; readonly success: (data: unknown, status?: number) => Response; }
export async function routeKnowledgeManager(request: Request, service: KnowledgeManagerService, context: KnowledgeManagerRouteContext): Promise<Response | undefined> { const url = new URL(request.url); if (!url.pathname.startsWith("/v1/knowledge-manager")) return undefined; const segments = url.pathname.split("/").filter(Boolean); const actor = principal(context.principal); try {
  if (segments.length === 3 && segments[2] === "bases" && request.method === "GET") return context.success(await service.listBases(actor, { search: url.searchParams.get("search") ?? undefined, page: Number(url.searchParams.get("page") ?? 1), pageSize: Number(url.searchParams.get("pageSize") ?? 20) }));
  if (segments.length === 3 && segments[2] === "bases" && request.method === "POST") { const data = body(await context.readJson()); if (typeof data.name !== "string") throw new BackendApiError("BAD_REQUEST", "name es obligatorio.", 400); return context.success(await service.createBase(actor, { name: data.name, ...(typeof data.description === "string" ? { description: data.description } : {}) }), 201); }
  if (segments.length === 4 && segments[2] === "bases" && request.method === "GET") return context.success(await service.getBase(actor, segments[3] ?? ""));
  if (segments.length === 4 && segments[2] === "bases" && request.method === "PATCH") { const data = body(await context.readJson()); return context.success(await service.updateBase(actor, segments[3] ?? "", { ...(typeof data.name === "string" ? { name: data.name } : {}), ...(typeof data.description === "string" ? { description: data.description } : {}) })); }
  if (segments.length === 5 && segments[2] === "bases" && segments[4] === "duplicate" && request.method === "POST") return context.success(await service.duplicateBase(actor, segments[3] ?? ""), 201);
  if (segments.length === 5 && segments[2] === "bases" && segments[4] === "archive" && request.method === "POST") return context.success(await service.archiveBase(actor, segments[3] ?? ""));
  if (segments.length === 5 && segments[2] === "bases" && segments[4] === "restore" && request.method === "POST") return context.success(await service.restoreBase(actor, segments[3] ?? ""));
  if (segments.length === 4 && segments[2] === "bases" && request.method === "DELETE") return context.success({ deleted: await service.deleteBase(actor, segments[3] ?? "") });
  if (segments.length === 5 && segments[2] === "bases" && segments[4] === "documents" && request.method === "GET") return context.success(await service.listDocuments(actor, segments[3] ?? ""));
  if (segments.length === 3 && segments[2] === "statistics" && request.method === "GET") return context.success(await service.statistics(actor));
  if (segments.length === 3 && segments[2] === "activity" && request.method === "GET") return context.success(await service.activity(actor));
  if (segments.length === 6 && segments[2] === "bases" && segments[4] === "assistants" && request.method === "POST") return context.success(await service.associateAssistant(actor, segments[3] ?? "", segments[5] ?? ""));
  if (segments.length === 6 && segments[2] === "bases" && segments[4] === "assistants" && request.method === "DELETE") return context.success(await service.disassociateAssistant(actor, segments[3] ?? "", segments[5] ?? ""));
  throw new BackendApiError("NOT_FOUND", "Ruta de Knowledge Manager no encontrada.", 404);
  } catch (error) { normalize(error); }
}
