import type {AdminPage,AdminQuery,AdminRecord,AdminResource,AdminValue,EnterpriseAdminService,EnterprisePrincipal,EnterpriseSummary} from "./enterpriseAdmin.types";
const FIXED_NOW="2026-08-04T12:00:00.000Z";
const initialFixtures=():Readonly<Partial<Record<AdminResource,readonly AdminRecord[]>>>=>Object.freeze({
 tenants:Object.freeze([{id:"development-tenant",tenantId:"development-tenant",name:"Empresa Demo",slug:"empresa-demo",status:"active",plan:"business",users:3,assistants:1,createdAt:FIXED_NOW},{id:"tenant-north",tenantId:"tenant-north",name:"Northwind Demo",slug:"northwind-demo",status:"trial",plan:"starter",users:2,assistants:1,createdAt:FIXED_NOW}]),
 users:Object.freeze([{id:"developer-user",tenantId:"development-tenant",name:"Alex Admin",email:"admin@example.test",role:"platform-admin",status:"active",assistantIds:Object.freeze(["support-assistant"])},{id:"operator-1",tenantId:"development-tenant",name:"Operador Demo",email:"operator@example.test",role:"operator",status:"active",assistantIds:Object.freeze([])},{id:"north-admin",tenantId:"tenant-north",name:"North Admin",email:"north@example.test",role:"tenant-admin",status:"active",assistantIds:Object.freeze([])}]),
 invitations:Object.freeze([{id:"invite-1",tenantId:"development-tenant",email:"new@example.test",role:"user",status:"pending",expiresAt:"2026-08-11T12:00:00.000Z",tokenHint:"dev-…-001"}]),
 roles:Object.freeze(["guest","user","operator","assistant-admin","tenant-admin","platform-admin"].map((name,index)=>Object.freeze({id:`role-${index+1}`,tenantId:name==="platform-admin"?"platform":"development-tenant",name,status:"active",scope:name==="platform-admin"?"platform":"tenant",permissions:Object.freeze(index>3?["users:read","assistants:read","metrics:read"]:["assistants:read"])}))),
 permissions:Object.freeze([{id:"permissions-catalog",tenantId:"platform",name:"Catálogo RBAC",count:43,status:"active"}]),
 assistants:Object.freeze([{id:"support-assistant",tenantId:"development-tenant",name:"Asistente de soporte",status:"published",version:"1.2.0",provider:"deterministic",model:"offline-test-model",knowledgeBaseIds:Object.freeze(["kb-handbook"]),toolIds:Object.freeze(["calculator"])}]),
 knowledge:Object.freeze([{id:"kb-handbook",tenantId:"development-tenant",name:"Manual interno",status:"active",documents:2,chunks:14,assistantIds:Object.freeze(["support-assistant"])}]),
 documents:Object.freeze([{id:"document-1",tenantId:"development-tenant",name:"Guía operativa.md",type:"text/markdown",status:"ready",knowledgeBaseId:"kb-handbook",size:4096,version:2,chunks:8,checksum:"8ac192e1…"},{id:"document-2",tenantId:"development-tenant",name:"Preguntas.csv",type:"text/csv",status:"ready",knowledgeBaseId:"kb-handbook",size:2048,version:1,chunks:6,checksum:"00bd821a…"}]),
 ingestion:Object.freeze([{id:"job-1",tenantId:"development-tenant",name:"Ingesta manual",status:"completed",progress:100,documents:2,chunks:14,deduplicated:1,durationMs:128}]),
 conversations:Object.freeze([{id:"conversation-1",tenantId:"development-tenant",assistantId:"support-assistant",userId:"operator-1",status:"completed",message:"[CONTENIDO REDACTADO]",citations:2,toolCalls:1,tokens:482,durationMs:734}]),
 tools:Object.freeze([{id:"calculator",tenantId:"platform",name:"Calculadora offline",category:"utility",risk:"safe",version:"1.0.0",status:"enabled",confirmation:false},{id:"date-time",tenantId:"platform",name:"Fecha determinista",category:"utility",risk:"safe",version:"1.0.0",status:"enabled",confirmation:false}]),
 providers:Object.freeze([{id:"deterministic",tenantId:"platform",name:"Proveedor offline",models:Object.freeze(["offline-test-model"]),embeddings:true,status:"available",health:"simulated"},{id:"openai",tenantId:"platform",name:"OpenAI",models:Object.freeze(["configurable"]),embeddings:true,status:"not-configured",health:"not-checked"}]),
 usage:Object.freeze([{id:"usage-current",tenantId:"development-tenant",period:"2026-08",requests:128,conversations:42,messages:310,inputTokens:22000,outputTokens:8000,totalTokens:30000,retrievals:80,chunks:320,toolCalls:18,errors:3,activeUsers:3,activeAssistants:1}]),
 costs:Object.freeze([{id:"cost-current",tenantId:"development-tenant",period:"2026-08",currency:"USD",estimated:true,billed:false,pricing:"manual development",inputCost:0.022,outputCost:0.024,embeddingCost:0.003,toolCost:0,total:0.049}]),
 metrics:Object.freeze([{id:"metrics-current",tenantId:"development-tenant",requests:128,successRate:97.7,errorRate:2.3,latencyP95:940,tokens:30000,retrievalQuality:91,citations:74,toolSuccess:100,memoryEntries:26,ingestionMs:128}]),
 audit:Object.freeze([{id:"audit-1",tenantId:"development-tenant",timestamp:FIXED_NOW,actorId:"developer-user",resourceType:"assistant",resourceId:"support-assistant",action:"assistant.published",status:"success",requestId:"request-fixture",correlationId:"correlation-fixture",metadata:"redacted"}]),
 security:Object.freeze([{id:"policy-development",tenantId:"development-tenant",sessionTimeoutMinutes:60,inactivityTimeoutMinutes:20,allowedOrigins:Object.freeze(["http://localhost:5173"]),allowedDomains:Object.freeze(["example.test"]),maximumUsers:25,maximumAssistants:10,maximumDocuments:500,bodyLimitBytes:65536,maximumToolRisk:"medium",requiredConfirmations:true,memoryEnabled:true,longTermMemoryAllowed:false,retentionDays:90,auditRetentionDays:180,ipAllowlist:Object.freeze([]),dataExportAllowed:true,conversationExportAllowed:false}]),
 settings:Object.freeze([{id:"settings-development",tenantId:"development-tenant",name:"Empresa Demo",slug:"empresa-demo",description:"Entorno empresarial determinista",logoUrl:"",primaryColor:"#2563eb",secondaryColor:"#7c3aed",language:"es",timezone:"America/Guayaquil",locale:"es-EC",allowedDomains:Object.freeze(["example.test"]),contact:"admin@example.test",support:"support@example.test",ragPolicy:"private-strict",memoryPolicy:"consent-required",toolsPolicy:"allowlist"}]),
 status:Object.freeze(["Backend/API","Assistant Runtime","Chat Providers","Embedding Providers","Knowledge Platform","Memory","Tools","Ingestion","Widget","Repositories","Rate limiter"].map((name,index)=>Object.freeze({id:`component-${index+1}`,tenantId:"platform",name,status:index===3?"not-configured":"operational",source:"deterministic development"})))
});
const csvCell=(value:AdminValue):string=>`"${(Array.isArray(value)?value.join("|"):String(value??"")).replaceAll('"','""')}"`;
/** Adaptador no productivo: datos volátiles, reloj e IDs deterministas. */
export class InMemoryEnterpriseAdminService implements EnterpriseAdminService{
 public readonly principal:EnterprisePrincipal; private readonly data=new Map<AdminResource,Map<string,AdminRecord>>();private sequence=100;
 public constructor(principal:EnterprisePrincipal,fixtures=initialFixtures()){this.principal=principal;for(const [resource,items] of Object.entries(fixtures))this.data.set(resource as AdminResource,new Map((items??[]).map(item=>[String(item.id),Object.freeze({...item})])));}
 public has(permission:string):boolean{return this.principal.roles.includes("platform-admin")||this.principal.permissions.includes(permission);}
 private visible(item:AdminRecord):boolean{return this.principal.roles.includes("platform-admin")||item.tenantId===this.principal.tenantId||item.tenantId==="platform";}
 public async list(resource:AdminResource,query:AdminQuery):Promise<AdminPage>{let items=[...(this.data.get(resource)?.values()??[])].filter(item=>this.visible(item));if(query.tenantId)items=items.filter(item=>item.tenantId===query.tenantId);if(query.search){const needle=query.search.toLocaleLowerCase();items=items.filter(item=>JSON.stringify(item).toLocaleLowerCase().includes(needle));}const field=query.sort??"id";items.sort((a,b)=>String(a[field]??"").localeCompare(String(b[field]??""))*(query.direction==="desc"?-1:1));const start=(query.page-1)*query.pageSize;return Object.freeze({items:Object.freeze(items.slice(start,start+query.pageSize)),page:query.page,pageSize:query.pageSize,total:items.length,hasNext:start+query.pageSize<items.length,hasPrevious:query.page>1});}
 public async create(resource:AdminResource,input:AdminRecord):Promise<AdminRecord>{const tenantId=String(input.tenantId??this.principal.tenantId);if(!this.principal.roles.includes("platform-admin")&&tenantId!==this.principal.tenantId)throw new Error("No se permite acceso cruzado entre tenants.");const id=String(input.id??`${resource.slice(0,-1)}-${++this.sequence}`);const record=Object.freeze({...input,id,tenantId,status:input.status??"active",createdAt:FIXED_NOW});this.bucket(resource).set(id,record);this.audit(resource,id,"created",tenantId);return record;}
 public async update(resource:AdminResource,id:string,input:AdminRecord):Promise<AdminRecord>{const old=this.bucket(resource).get(id);if(old===undefined||!this.visible(old))throw new Error("Recurso no encontrado.");const tenantId=String(input.tenantId??old.tenantId);if(!this.principal.roles.includes("platform-admin")&&tenantId!==old.tenantId)throw new Error("Transferencia de tenant no autorizada.");const record=Object.freeze({...old,...input,id,tenantId,updatedAt:FIXED_NOW});this.bucket(resource).set(id,record);this.audit(resource,id,"updated",tenantId);return record;}
 public async archive(resource:AdminResource,id:string):Promise<boolean>{const old=this.bucket(resource).get(id);if(old===undefined||!this.visible(old))return false;this.bucket(resource).set(id,Object.freeze({...old,status:"archived",updatedAt:FIXED_NOW}));this.audit(resource,id,"archived",String(old.tenantId));return true;}
 public async summary():Promise<EnterpriseSummary>{const count=(resource:AdminResource)=>[...(this.data.get(resource)?.values()??[])].filter(item=>this.visible(item)).length;const usage=(await this.list("usage",{page:1,pageSize:1})).items[0];const costs=(await this.list("costs",{page:1,pageSize:1})).items[0];return Object.freeze({tenants:count("tenants"),users:count("users"),assistants:count("assistants"),documents:count("documents"),conversations:count("conversations"),toolCalls:Number(usage?.toolCalls??0),errors:Number(usage?.errors??0),tokens:Number(usage?.totalTokens??0),estimatedCost:Number(costs?.total??0),developmentData:true});}
 public async export(resource:AdminResource,format:"json"|"csv"):Promise<string>{const items=(await this.list(resource,{page:1,pageSize:100})).items.map(item=>Object.fromEntries(Object.entries(item).filter(([key])=>!/token|secret|content|message/i.test(key))));if(format==="json")return JSON.stringify(items,null,2);const headers=[...new Set(items.flatMap(item=>Object.keys(item)))];return [headers.map(csvCell).join(","),...items.map(item=>headers.map(header=>csvCell((item[header]??null) as AdminValue)).join(","))].join("\n");}
 private bucket(resource:AdminResource):Map<string,AdminRecord>{const bucket=this.data.get(resource)??new Map<string,AdminRecord>();this.data.set(resource,bucket);return bucket;}
 private audit(resource:string,id:string,action:string,tenantId:string):void{const audit=this.bucket("audit");const auditId=`audit-${++this.sequence}`;audit.set(auditId,Object.freeze({id:auditId,tenantId,timestamp:FIXED_NOW,actorId:this.principal.actorId,resourceType:resource,resourceId:id,action,status:"success",requestId:`request-${this.sequence}`,correlationId:`correlation-${this.sequence}`,metadata:"redacted"}));}
}
export interface BackendEnterpriseAdminServiceConfig{readonly baseUrl:string;readonly principal:EnterprisePrincipal;readonly tokenProvider:()=>string|undefined;readonly fetchImplementation?:typeof fetch;readonly timeoutMilliseconds?:number;}
export class BackendEnterpriseAdminService implements EnterpriseAdminService{public readonly principal:EnterprisePrincipal;private readonly fetcher:typeof fetch;public constructor(private readonly config:BackendEnterpriseAdminServiceConfig){this.principal=config.principal;this.fetcher=config.fetchImplementation??fetch;}public has(permission:string):boolean{return this.principal.roles.includes("platform-admin")||this.principal.permissions.includes(permission as never);}private async request(path:string,init:RequestInit={},signal?:AbortSignal):Promise<unknown>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort("timeout"),this.config.timeoutMilliseconds??10000);const abort=()=>controller.abort(signal?.reason);signal?.addEventListener("abort",abort,{once:true});try{const token=this.config.tokenProvider();const response=await this.fetcher(`${this.config.baseUrl}${path}`,{...init,signal:controller.signal,headers:{accept:"application/json",...(init.body!==undefined?{"content-type":"application/json"}:{}),...(token?{authorization:`Bearer ${token}`}:{})}});const text=await response.text();const body=JSON.parse(text) as {readonly success?:boolean;readonly data?:unknown;readonly error?:{readonly message?:string}};if(!response.ok||body.success!==true)throw new Error(body.error?.message??`Error administrativo ${response.status}.`);return body.data;}finally{clearTimeout(timeout);signal?.removeEventListener("abort",abort);}}
 public async list(resource:AdminResource,query:AdminQuery,signal?:AbortSignal):Promise<AdminPage>{const params=new URLSearchParams({page:String(query.page),pageSize:String(query.pageSize)});if(query.search)params.set("search",query.search);if(query.tenantId)params.set("tenantId",query.tenantId);return await this.request(`/v1/admin/${resource}?${params}`,{},signal) as AdminPage;}
 public async create(resource:AdminResource,input:AdminRecord):Promise<AdminRecord>{return await this.request(`/v1/admin/${resource}`,{method:"POST",body:JSON.stringify(input)}) as AdminRecord;}public async update(resource:AdminResource,id:string,input:AdminRecord):Promise<AdminRecord>{return await this.request(`/v1/admin/${resource}/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)}) as AdminRecord;}public async archive(resource:AdminResource,id:string):Promise<boolean>{const value=await this.request(`/v1/admin/${resource}/${encodeURIComponent(id)}`,{method:"DELETE"}) as {readonly archived?:boolean};return value.archived===true;}public async summary():Promise<EnterpriseSummary>{const metrics=await this.list("metrics",{page:1,pageSize:1});const row=metrics.items[0];return Object.freeze({tenants:0,users:0,assistants:0,documents:0,conversations:0,toolCalls:Number(row?.toolCalls??0),errors:Number(row?.errors??0),tokens:Number(row?.tokens??0),estimatedCost:Number(row?.costs??0),developmentData:true});}public async export(resource:AdminResource,format:"json"|"csv"):Promise<string>{const page=await this.list(resource,{page:1,pageSize:100});return format==="json"?JSON.stringify(page.items,null,2):page.items.map(item=>JSON.stringify(item)).join("\n");}}
